version: '3.8'

services:
  maps-app:
    build: 
      context: .
      dockerfile: Dockerfile.fixed
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=AIzaSyAx7pp7zNpmxL05hJi-LCAMAYudm7kuCP4
    restart: unless-stopped
    volumes:
      - ./data:/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - maps-network

networks:
  maps-network:
    driver: bridge
